//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SailawayToNMEA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SailawayToNMEA.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not auto launch the specified program.
        /// </summary>
        internal static string AutoLaunchProgramProblem {
            get {
                return ResourceManager.GetString("AutoLaunchProgramProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected boat data refreshed from Sailaway server.
        /// </summary>
        internal static string BoatDataRefreshed {
            get {
                return ResourceManager.GetString("BoatDataRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected boat data refreshed by dead reckoning (estimated position).
        /// </summary>
        internal static string BoatDataRefreshedDeadReckoning {
            get {
                return ResourceManager.GetString("BoatDataRefreshedDeadReckoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boat passed in arguments was not found.
        /// </summary>
        internal static string BoatNotFound {
            get {
                return ResourceManager.GetString("BoatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client connected from .
        /// </summary>
        internal static string ClientConnected {
            get {
                return ResourceManager.GetString("ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimates your new position each minute based on speed and heading.
        /// </summary>
        internal static string DeadReckoningExplanation {
            get {
                return ResourceManager.GetString("DeadReckoningExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMEA sent:.
        /// </summary>
        internal static string NMEASent {
            get {
                return ResourceManager.GetString("NMEASent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMEA Server Error: .
        /// </summary>
        internal static string NMEAServerError {
            get {
                return ResourceManager.GetString("NMEAServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMEA server started in port.
        /// </summary>
        internal static string NMEAServerStarted {
            get {
                return ResourceManager.GetString("NMEAServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMEA server stopped.
        /// </summary>
        internal static string NMEAServerStopped {
            get {
                return ResourceManager.GetString("NMEAServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh rate set to .
        /// </summary>
        internal static string RequestRateInformation {
            get {
                return ResourceManager.GetString("RequestRateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailaway connection problem: .
        /// </summary>
        internal static string SailawayConnectionProblem {
            get {
                return ResourceManager.GetString("SailawayConnectionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User boats data retrieved from Sailaway server.
        /// </summary>
        internal static string UserBoatsRetrieved {
            get {
                return ResourceManager.GetString("UserBoatsRetrieved", resourceCulture);
            }
        }
    }
}
