//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SailawayToNMEA.Resources ***REMOVED***
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts ***REMOVED***
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager ***REMOVED***
            get ***REMOVED***
                if (object.ReferenceEquals(resourceMan, null)) ***REMOVED***
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SailawayToNMEA.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
            ***REMOVED***
                return resourceMan;
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture ***REMOVED***
            get ***REMOVED***
                return resourceCulture;
        ***REMOVED***
            set ***REMOVED***
                resourceCulture = value;
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected boat data refreshed.
        /// </summary>
        internal static string BoatDataRefreshed ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("BoatDataRefreshed", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boats refreshed.
        /// </summary>
        internal static string BoatsRefreshed ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("BoatsRefreshed", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retrieving initial data from Sailaway server....
        /// </summary>
        internal static string InitialLoad ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("InitialLoad", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a NMEA sent:.
        /// </summary>
        internal static string NMEASent ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("NMEASent", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a NMEA server started in port.
        /// </summary>
        internal static string NMEAServerStarted ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("NMEAServerStarted", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a NMEA server stopped.
        /// </summary>
        internal static string NMEAServerStoped ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("NMEAServerStoped", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        internal static string Start ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("Start", resourceCulture);
        ***REMOVED***
    ***REMOVED***
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop.
        /// </summary>
        internal static string Stop ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("Stop", resourceCulture);
        ***REMOVED***
    ***REMOVED***
***REMOVED***
***REMOVED***
